CREATE TABLE TESTES.ALUNO (
    ID INTEGER PRIMARY KEY NOT NULL,
    DES_NOME VARCHAR (255),
    NUM_GRAU INT
);

CREATE TABLE TESTES.AMIGO (
    FK_ALUNO INT,
    CONSTRAINT FK_AMIGO_ALUNO FOREIGN KEY(FK_ALUNO) REFERENCES TESTES.ALUNO(ID)
);

ALTER TABLE TESTES.AMIGO ADD COLUMN NOME VARCHAR(50);


CREATE TABLE TESTES.CURTIDA (

    FK_ALUNO INT,
    CONSTRAINT FK_CURTIDA_ALUNO FOREIGN KEY(FK_ALUNO) REFERENCES TESTES.ALUNO(ID)
);

ALTER TABLE TESTES.CURTIDA ADD COLUMN NOME VARCHAR(50);


INSERT INTO TESTES.ALUNO VALUES (1, 'AMANDA', 2);
INSERT INTO TESTES.ALUNO VALUES (2, 'LUIZ VICTOR', 2);
INSERT INTO TESTES.ALUNO VALUES (3, 'ISABELLA', 2);

SELECT * FROM TESTES.ALUNO;

INSERT INTO TESTES.AMIGO VALUES(1, 'GABRIELA');
INSERT INTO TESTES.AMIGO VALUES(2, 'JOÃO');

SELECT * FROM TESTES.AMIGO;

INSERT INTO TESTES.CURTIDA VALUES (1, 'SUZANA');
INSERT INTO TESTES.CURTIDA VALUES (1, 'LUCAS');

SELECT * FROM TESTES.CURTIDA;

SELECT * FROM TESTES.ALUNO INNER JOIN TESTES.AMIGO ON ALUNO.ID = AMIGO.FK_ALUNO;
