CREATE TABLE USUARIO (
    ID INT PRIMARY KEY NOT NULL,
    NOME VARCHAR (50),
    EMAIL VARCHAR (100)
);

CREATE TABLE CARGO (
    ID INT PRIMARY KEY NOT NULL,
    NOME VARCHAR (50),
    FK_USUARIO INT,
    CONSTRAINT FK_CARGO_USUARIO FOREIGN KEY(FK_USUARIO) REFERENCES USUARIO(ID)
);



INSERT INTO USUARIO VALUES(1, 'AMANDA', 'AMANDA.EMAIL@GMAIL.COM');
INSERT INTO USUARIO VALUES(2, 'JOSE', 'JOSE.EMAIL@GMAIL.COM');
INSERT INTO USUARIO VALUES(3, 'LUIZ', 'LUIZ.EMAIL@GMAIL.COM');

INSERT INTO CARGO VALUES(1, 'PRESIDENTE', 1);
INSERT INTO CARGO VALUES(2, 'VICE', 2);
INSERT INTO CARGO VALUES(3, 'GERENTE', 3);



-- CONSULTA TOTAL

SELECT * FROM USUARIO;
SELECT * FROM CARGO;

-- LEFT JOIN que retorna todos os usuários e seus cargod
-- os registros da tebla da esquerda (usuario) e os registros da tabela da direita (cargo)
SELECT * FROM USUARIO LEFT JOIN CARGO ON USUARIO.ID = CARGO.FK_USUARIO; -- começa a pesquisa pela esquerda (usuario)

SELECT * FROM USUARIO RIGHT JOIN CARGO ON USUARIO.ID = CARGO.FK_USUARIO; -- começa a pesquisa pela direita (cargo)

-- Inner Join que retorna todos os registros quando houver uma correspondência entre as tabelas 
SELECT * FROM USUARIO INNER JOIN CARGO ON USUARIO.ID = CARGO.FK_USUARIO;

